name: Update Pipeline

on:
  push:
    paths:
      - 'ci/**'

jobs:
  update-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Install Fly CLI
        run: |
          curl 'https://build.cqgc.hsj.rtss.qc.ca/api/v1/cli?arch=amd64&platform=linux' -o fly \
            && chmod +x ./fly && mv ./fly /usr/local/bin/

      - name: Configure Fly CLI
        run: |
          fly -t main login -c https://build.cqgc.hsj.rtss.qc.ca --username ${{ secrets.CONCOURSE_USERNAME }} --password ${{ secrets.CONCOURSE_PASSWORD }}

      - name: Set Pipeline
        run: |
          fly -t main sp -n -p clin-portal-ui -c ./ci/pipeline.yml
